import * as THREE from 'three'
import { measureHeadFit } from './avatarCustomization'
import {
  CH,
  EMOTION_COUNT,
  EMOTION_INDEX,
  createEmotionState,
  createFaceContext,
  emotionArousal,
  emotionHeaviness,
  updateBlink,
  updateEmotion,
  type EmotionState,
  type FaceContext,
  type FaceEmotion,
} from './avatarFaceEmotion'
import {
  IRIS_PALETTE,
  createEyeDomeGeometry,
  createEyeMaterial,
  createEyeUniforms,
  type EyeUniforms,
} from './avatarFaceEyes'
import {
  GAZE,
  createGazeState,
  createGazeTargets,
  gazeVector,
  updateGaze,
  type GazeEye,
  type GazeOptions,
  type GazeState,
  type GazeTargets,
} from './avatarFaceGaze'
import { createMouth, createMouthGeometry, updateMouth, type FaceMouth, type MouthShape } from './avatarFaceMouth'
import {
  acquireOverlayAtlas,
  createOverlay,
  createOverlayMaterial,
  releaseOverlayAtlas,
  updateBrows,
  updateOverlayColors,
  type BrowParams,
  type DecalKind,
  type DecalSpec,
  type FaceOverlay,
} from './avatarFaceOverlay'
import { faceHash01, getFacePersonality, type FacePersonality, type FacePersonalityInput } from './avatarFacePersonality'
import { installFacialHairShade, type FacialHairShade } from './avatarFaceHair'
import { createFaceSurface } from './avatarFaceSurface'

/**
 * Expressive faces for the rigged avatars.
 *
 * The source models paint tiny eyes and brows onto the head. We locate those
 * painted regions in the skinned mesh (by material name), hide them, and mount
 * real, procedural features on the Head bone at the same spots:
 *   - eyes (avatarFaceEyes): one shader dome each, with real lids that close,
 *     almond shape, lashes, iris detail, dilating pupil, wet catch-lights;
 *   - brows + skin decals (avatarFaceOverlay): one mesh for both brows, blush,
 *     eye bags, sheen, pallor and crease lines;
 *   - mouth (avatarFaceMouth): lips, teeth, tongue, asymmetric corners.
 * Emotion (avatarFaceEmotion), gaze (avatarFaceGaze) and the per-seat director
 * (avatarFaceDirector) drive them. Cost per face: 2 eye draws + 1 overlay + 1 mouth.
 */

export type FaceMood = 'neutral' | 'focused' | 'surprised' | 'happy' | 'sad' | 'bored'

export interface EyeRig {
  /** Positioned/rotated/scaled (uniform, = eye radius) on the Head bone; +Z faces out of the head. */
  root: THREE.Group
  dome: THREE.Mesh
  uniforms: EyeUniforms
  /** Head-space eye radius (the nominal radius, before glasses fitting). */
  radius: number
  side: 1 | -1
}

export interface FaceInput {
  delta: number
  /** Forced eyelid closure 0..1 (passed out). Natural blinks are generated by the face itself. */
  blink: number
  /** Legacy/debug coarse mood, used only when no game context is supplied. */
  mood?: FaceMood
  /** Legacy look direction (fallback when no gaze targets are available). */
  lookX: number
  lookY: number
  reducedMotion: boolean
  folded?: boolean
  hasContext?: boolean
  /** Camera distance to the head (world units), for level of detail. */
  distance?: number
  /** The director skipped this frame (far-away face, level of detail). */
  skip?: boolean
}

export interface AvatarFaceRig {
  eyes: EyeRig[]
  overlay: FaceOverlay
  mouth: FaceMouth
  materials: THREE.Material[]
  geometries: THREE.BufferGeometry[]
  /** Painted-over eye/brow patches and eye domes: they follow the live skin colour (flush, folded shading). */
  skinFollowers: THREE.MeshToonMaterial[]
  skinSource: THREE.MeshToonMaterial | null
  /** The Head bone the face is mounted on. */
  headBone: THREE.Bone
  /**
   * Where a forehead sticker goes, in Head space: on the skin surface above the brows,
   * facing forward and tilted up with the slope of the brow. `unit` is the eye radius.
   */
  forehead: { position: THREE.Vector3; quaternion: THREE.Quaternion; unit: number; size: number }
  personality: FacePersonality
  emotion: EmotionState
  gazeState: GazeState
  gazeTargets: GazeTargets
  /** Reused per-frame inputs, filled by the director. */
  input: FaceInput
  context: FaceContext
  targets: GazeTargets
  gazeEyes: GazeEye[]
  gazeOpts: GazeOptions
  eyewear: string
  /** Painted eye/brow materials hidden while the face is mounted. */
  hiddenMaterials: THREE.Material[]
  /** Brow thickness multiplier (thicker on dark skin where dark brows lose contrast). */
  browContrast: number
  /** Undoes the skin grade wrapper. */
  restoreSkin: (() => void) | null
  /** Shade on a light moustache (null when the model has none / dark hair). */
  hairShade: FacialHairShade | null
  /** Skeletons of this avatar, refreshed right before each render (see syncSkeletons). */
  skeletons: THREE.Skeleton[]
  sceneHooked: boolean
  /** The scene the skeleton-sync hook lives on (checked every update, see ensureSceneHook). */
  scene: THREE.Object3D | null
  /** A table emote the face is reacting to (set by the director, expires on the face clock). */
  emote: { emotion: FaceEmotion; until: number; amount: number } | null
  state: {
    seed: number
    time: number
    frame: number
    accumDelta: number
    strideFrame: number
    phase: number
    dim: number
    pupil: number
    debugWeights: Float32Array
    lossStreak: number
    prevLoser: boolean
    prevWinner: boolean
    /** The director last saw this seat in a table conversation (to retarget the eyes when it starts). */
    prevChatting?: boolean
    lastBrowAlpha: number
    mouthShape: MouthShape
    browParams: BrowParams
    alphas: Partial<Record<DecalKind, number>>
  }
}

/** Collects the bind-pose positions (in Head-bone space) of vertices painted with a material. */
function collectRegion(
  model: THREE.Object3D,
  headBone: THREE.Bone,
  materialPattern: RegExp
): THREE.Vector3[] {
  const points: THREE.Vector3[] = []
  model.traverse(object => {
    const mesh = object as THREE.SkinnedMesh
    if (!mesh.isSkinnedMesh || !mesh.material) return
    const headIndex = mesh.skeleton.bones.indexOf(headBone)
    if (headIndex < 0) return
    const toHead = new THREE.Matrix4().multiplyMatrices(mesh.skeleton.boneInverses[headIndex]!, mesh.bindMatrix)
    const position = mesh.geometry.getAttribute('position')
    const index = mesh.geometry.getIndex()
    const materials = Array.isArray(mesh.material) ? mesh.material : [mesh.material]
    // GLTF splits multi-material meshes into one primitive per material, so a
    // single-material mesh has no groups: treat it as one group spanning it all.
    const groups = mesh.geometry.groups.length > 0
      ? mesh.geometry.groups
      : [{ start: 0, count: index ? index.count : position.count, materialIndex: 0 }]
    for (const group of groups) {
      const material = materials[group.materialIndex ?? 0]
      if (!material || !materialPattern.test(material.name)) continue
      for (let cursor = group.start; cursor < group.start + group.count; cursor += 1) {
        const vertex = index ? index.getX(cursor) : cursor
        points.push(new THREE.Vector3().fromBufferAttribute(position, vertex).applyMatrix4(toHead))
      }
    }
  })
  return points
}

function splitBySide(points: THREE.Vector3[]) {
  const center = points.reduce((sum, point) => sum.add(point), new THREE.Vector3()).divideScalar(Math.max(1, points.length))
  const left = points.filter(point => point.x < center.x)
  const right = points.filter(point => point.x >= center.x)
  const box = (list: THREE.Vector3[]) => new THREE.Box3().setFromPoints(list)
  return { center, left: left.length ? box(left) : null, right: right.length ? box(right) : null }
}

/** Hides the painted eyes/brows by matching them to the skin tone. */
function paintOver(materials: readonly THREE.Material[], pattern: RegExp, skin: THREE.Color | null) {
  if (!skin) return
  for (const material of materials) {
    const tinted = material as THREE.MeshToonMaterial
    if (pattern.test(material.name) && tinted.color) tinted.color.copy(skin)
  }
}

/**
 * Skinned meshes and the things rigidly attached to bones (eyes, brows, mouth, glasses, hats) must
 * agree on the pose every frame. three.js refreshes a skeleton at most once per renderer frame
 * counter, and the shadow pass (which only runs on some frames here) bumps that counter and
 * refreshes the skeleton itself. On the frame after a shadow pass the main pass therefore reuses
 * bone matrices from the PREVIOUS frame, while rigid children use the current ones: the skin lags
 * one frame and, during quick head motion, swallows everything mounted on it (blank faces).
 * Fix: refresh every avatar skeleton from the final bone matrices right before each render
 * (Scene.onBeforeRender runs after the matrices are updated and before the skeletons are read).
 */
interface SyncedSkeleton {
  skeleton: THREE.Skeleton
  update: () => void
  stamp: number
}
const syncedSkeletons: SyncedSkeleton[] = []
let syncToken = 0

/** Our pre-render hook per scene, plus a watchdog (see ensureSceneHook). */
interface SceneHook {
  hook: NonNullable<THREE.Object3D['onBeforeRender']>
  /** Times the hook ran; `seen` is the value at the last check, `stall` the checks since it moved. */
  runs: number
  seen: number
  stall: number
}
const sceneHooks = new WeakMap<THREE.Object3D, SceneHook>()

function collectSkeletons(model: THREE.Object3D) {
  const list: THREE.Skeleton[] = []
  model.traverse(object => {
    const mesh = object as THREE.SkinnedMesh
    if (mesh.isSkinnedMesh && mesh.skeleton && !list.includes(mesh.skeleton)) list.push(mesh.skeleton)
  })
  return list
}

function registerSkeleton(skeleton: THREE.Skeleton) {
  if (syncedSkeletons.some(entry => entry.skeleton === skeleton)) return
  const entry: SyncedSkeleton = { skeleton, update: skeleton.update, stamp: -1 }
  // three's render pass calls skeleton.update() again after our refresh: skip that duplicate work
  // (same frame, same bones) so the sync is free. Outside a synced frame it behaves as before.
  skeleton.update = function (this: THREE.Skeleton) {
    if (entry.stamp === syncToken) return
    entry.update.call(this)
  }
  syncedSkeletons.push(entry)
}

function unregisterSkeleton(skeleton: THREE.Skeleton) {
  const index = syncedSkeletons.findIndex(entry => entry.skeleton === skeleton)
  if (index < 0) return
  delete (skeleton as { update?: () => void }).update // back to the prototype method
  syncedSkeletons.splice(index, 1)
}

function beforeSceneRender() {
  // (dev switch for A/B measurements: window.__faceNoSkeletonSync = true)
  if (process.env.NODE_ENV !== 'production' && (globalThis as { __faceNoSkeletonSync?: boolean }).__faceNoSkeletonSync) {
    syncToken += 1
    return
  }
  syncToken += 1
  for (let i = 0; i < syncedSkeletons.length; i += 1) {
    const entry = syncedSkeletons[i]!
    entry.update.call(entry.skeleton)
    entry.stamp = syncToken
  }
}

/** Wraps whatever scene.onBeforeRender currently is so the skeleton sync runs first-class after it. */
function installSceneHook(scene: THREE.Object3D) {
  const previous = scene.onBeforeRender
  const entry: SceneHook = {
    hook: function (this: THREE.Object3D, renderer, sceneArg, camera, geometry, material, group) {
      previous.call(this, renderer, sceneArg, camera, geometry, material, group)
      entry.runs += 1
      beforeSceneRender()
    },
    runs: 0,
    seen: 0,
    stall: 0,
  }
  sceneHooks.set(scene, entry)
  scene.onBeforeRender = entry.hook
}

/**
 * Watchdog, run cheaply on every face update: if some other code REPLACED scene.onBeforeRender
 * without chaining ours (faces would float off their heads), wrap the new one again. A hook that
 * chains ours keeps the run counter moving and is left alone; a paused renderer (no runs, but our
 * hook still installed) is left alone too, so wrappers never pile up.
 */
function ensureSceneHook(scene: THREE.Object3D) {
  const entry = sceneHooks.get(scene)
  if (!entry) {
    installSceneHook(scene)
    return
  }
  if (entry.runs !== entry.seen) {
    entry.seen = entry.runs
    entry.stall = 0
    return
  }
  entry.stall += 1
  if (entry.stall > 8 && scene.onBeforeRender !== entry.hook) installSceneHook(scene)
}

function hookSkeletonSync(face: AvatarFaceRig) {
  let node: THREE.Object3D = face.headBone
  while (node.parent) node = node.parent
  const scene = node as THREE.Scene
  if (!scene.isScene) return // not mounted yet: try again next frame
  face.sceneHooked = true
  face.scene = scene
  for (const skeleton of face.skeletons) registerSkeleton(skeleton)
  ensureSceneHook(scene)
}

const RIGGED_ACCESSORY_SCALE = 0.0043

/**
 * Where the procedural glasses' lenses sit for this head (mirrors createGlasses in
 * avatarCustomization), in Head space. Eyes are fitted inside so they never
 * overlap the frames or poke in front of the glass.
 */
function measureLenses(model: THREE.Object3D, headBone: THREE.Bone, style: string) {
  const fit = measureHeadFit(model, headBone, RIGGED_ACCESSORY_SCALE)
  if (!fit) return null
  const s = RIGGED_ACCESSORY_SCALE
  const maxOuter = fit.faceHalfWidth * 0.93
  const lensRadius = Math.min(0.1, Math.max(0.05, fit.eyeX * 0.82), Math.max(0.05, maxOuter - fit.eyeX))
  const eyeX = Math.max(lensRadius * 0.9, Math.min(fit.eyeX, maxOuter - lensRadius))
  const aviator = style === 'aviator'
  return {
    x: eyeX * s,
    y: fit.eyeY * s,
    /** Lens plane depth at the lens centre (Head units). */
    z: (fit.eyeFront + 0.024) * s,
    rx: lensRadius * s * (aviator ? 1.06 * 1.05 : 1),
    ry: lensRadius * s * (aviator ? 1.06 * 0.84 : 1),
    tilt: 0.22,
  }
}

const EYE_DOME_SCALE = new THREE.Vector3(0.64, 0.5, 0.36)
const EYE_APERTURE_HALF_WIDTH = 0.5
const SKIN_SATURATION = 0.88
/** Where the moustache's lower edge sits above the (lowered) mouth, in eye radii. */
const HAIR_EDGE_OFFSET = 0.3
/** Extra mouth-corner lift under facial hair (the moustache hides most of the smile). */
const FACIAL_HAIR_SMILE_BIAS = 0.12

export function createAvatarFace(
  model: THREE.Object3D,
  headBone: THREE.Bone | undefined,
  materials: readonly THREE.Material[],
  skinColor: THREE.Color | null,
  eyewear: 'none' | 'round' | 'aviator' | 'shades' | string = 'none',
  seed = 0.5,
  profile?: Partial<FacePersonalityInput>
): AvatarFaceRig | null {
  if (!headBone) return null
  const eyePoints = collectRegion(model, headBone, /^eye$/i)
  if (eyePoints.length < 6) return null
  const browPoints = collectRegion(model, headBone, /^eyebrows?$/i)

  const { center, left, right } = splitBySide(eyePoints)
  if (!left || !right) return null
  // Face forward in Head space: from the head origin through the eyes, flattened.
  const forward = new THREE.Vector3(center.x * 0, 0, center.z).normalize()
  if (forward.lengthSq() < 0.5) forward.set(0, 0, 1)
  const quaternion = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 0, 1), forward)
  const basis = {
    right: new THREE.Vector3(1, 0, 0).applyQuaternion(quaternion),
    up: new THREE.Vector3(0, 1, 0).applyQuaternion(quaternion),
    forward: forward.clone(),
  }

  const created: THREE.Material[] = []
  const geometries: THREE.BufferGeometry[] = []
  const personality = getFacePersonality({ ...profile, seed })

  const eyeWidth = Math.max(left.max.x - left.min.x, right.max.x - right.min.x)
  const eyeHeight = Math.max(left.max.y - left.min.y, right.max.y - right.min.y)
  const radius = Math.max(eyeWidth, eyeHeight) * 1.05

  // The face surface around the eyes (skin in Head space), so the eyes sit *on*
  // the head instead of bulging out of it in profile.
  const skinPoints = collectRegion(model, headBone, /^skin$/i)
  const surface = createFaceSurface(model, headBone, forward, {
    minY: center.y - radius * 9,
    maxY: center.y + radius * 7,
    maxX: radius * 10,
  })

  const skinSource = (materials.find(material => /^skin$/i.test(material.name)) as THREE.MeshToonMaterial | undefined) ?? null
  const gradientMap = skinSource?.gradientMap ?? null
  const skin = skinColor ?? new THREE.Color('#d9a37c')

  // Brow / hair colour comes from the painted brows before they are hidden.
  const browMaterial = materials.find(material => /^eyebrows?$/i.test(material.name)) as THREE.MeshToonMaterial | undefined
  const browColor = browMaterial?.color ? browMaterial.color.clone() : new THREE.Color('#2a1a12')
  if (skinColor && Math.abs(browColor.r - skinColor.r) + Math.abs(browColor.g - skinColor.g) + Math.abs(browColor.b - skinColor.b) < 0.03) browColor.set('#2a1a12')
  const skinLuma = skin.r * 0.299 + skin.g * 0.587 + skin.b * 0.114
  const browContrast = skinLuma < 0.22 ? 1.4 : 1
  const hairMaterial = materials.find(material => /^(hair|moustache|mustache|beard)$/i.test(material.name)) as THREE.MeshToonMaterial | undefined

  // ---- eyes ----
  const lenses = eyewear === 'round' || eyewear === 'aviator' ? measureLenses(model, headBone, eyewear) : null
  const domeGeometry = createEyeDomeGeometry()
  geometries.push(domeGeometry)
  const [irisA, irisB] = IRIS_PALETTE[personality.iris]
  const lashColor = browColor.clone().multiplyScalar(0.55).lerp(new THREE.Color('#120806'), 0.55)
  const eyes: EyeRig[] = []
  const eyeCenters: THREE.Vector3[] = []
  const skinFollowers: THREE.MeshToonMaterial[] = []
  for (const [box, side] of [[right, 1], [left, -1]] as const) {
    const eyeCenter = box.getCenter(new THREE.Vector3())
    let rootScale = radius
    let protrude = radius * 0.17
    if (lenses) {
      // Sit centred behind the lens, small enough to clear the frame, well behind the glass.
      const lensCenterX = side * lenses.x
      if (Math.abs(lensCenterX - eyeCenter.x) < radius * 1.2) eyeCenter.x = lensCenterX
      if (Math.abs(lenses.y - eyeCenter.y) < radius * 1.2) eyeCenter.y = lenses.y
      const fitWidth = (lenses.rx * 0.8) / (EYE_APERTURE_HALF_WIDTH * 1.05)
      const fitHeight = (lenses.ry * 0.86) / 0.38
      rootScale = Math.min(radius, fitWidth, fitHeight)
      protrude = radius * 0.1
    }
    const surfaceDepth = surface.depthAt(eyeCenter.x, eyeCenter.y) ?? eyeCenter.dot(forward) + radius * 0.3
    if (lenses) {
      // Never let the dome reach the lens plane (minus the lens tilt at its outer edge).
      const lensDepth = lenses.z - Math.sin(lenses.tilt) * rootScale * 0.7
      const room = lensDepth - surfaceDepth - radius * 0.06
      protrude = Math.max(radius * 0.02, Math.min(protrude, room))
    }
    eyeCenters.push(eyeCenter)
    const root = new THREE.Group()
    root.name = 'cartoon-eye'
    const along = eyeCenter.dot(forward)
    root.position.copy(eyeCenter).addScaledVector(forward, surfaceDepth + protrude - rootScale * EYE_DOME_SCALE.z - along)
    // Follow the curve of the face: each eye turns slightly outward.
    root.quaternion.copy(quaternion).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), side * 0.22))
    root.scale.setScalar(rootScale)

    const uniforms = createEyeUniforms(side)
    uniforms.uAper.value.z = EYE_APERTURE_HALF_WIDTH
    uniforms.uQScale.value.set(EYE_DOME_SCALE.x, EYE_DOME_SCALE.y)
    uniforms.uIrisA.value.set(irisA)
    uniforms.uIrisB.value.set(irisB)
    uniforms.uLash.value.copy(lashColor)
    const material = createEyeMaterial(uniforms, skin, gradientMap)
    created.push(material)
    skinFollowers.push(material as THREE.MeshToonMaterial)
    const dome = new THREE.Mesh(domeGeometry, material)
    dome.name = 'cartoon-eye-dome'
    dome.frustumCulled = false
    dome.scale.copy(EYE_DOME_SCALE)
    root.add(dome)
    headBone.add(root)
    eyes.push({ root, dome, uniforms, radius, side })
  }
  const eyeMid = eyeCenters[0]!.clone().lerp(eyeCenters[1]!, 0.5)

  // ---- mouth ----
  const mouthMaterial = new THREE.MeshToonMaterial({
    color: '#ffffff',
    vertexColors: true,
    side: THREE.DoubleSide,
    gradientMap,
    polygonOffset: true,
    polygonOffsetFactor: -2,
    polygonOffsetUnits: -2,
  })
  created.push(mouthMaterial)
  let mouthY = eyeMid.y - radius * 2.7
  const mouthHalfWidth = radius * 0.98
  // Facial hair (a moustache/beard mesh) hides a mouth that sits on the skin under it. Detect
  // it over the mouth's footprint; on those models the mouth drops just below the moustache
  // and sits in front of the hair, with tamer limits so it never pokes past it.
  let beardDepthGain = 0
  for (let c = 0; c < 13; c += 1) {
    const x = eyeMid.x + (c / 12 * 2 - 1) * mouthHalfWidth
    for (let k = -2; k <= 2; k += 1) {
      const y = mouthY + k * radius * 0.25
      const skinDepth = surface.depthAt(x, y)
      const hairDepth = surface.depthAt(x, y, true)
      if (skinDepth !== null && hairDepth !== null) beardDepthGain = Math.max(beardDepthGain, hairDepth - skinDepth)
    }
  }
  const hasFacialHair = beardDepthGain > radius * 0.12
  if (hasFacialHair) {
    // Step the mouth down until the centre of the lips is clear of the moustache (up to ~0.8r).
    mouthY -= radius * 0.3
    for (let step = 0; step < 2; step += 1) {
      const skinDepth = surface.depthAt(eyeMid.x, mouthY)
      const hairDepth = surface.depthAt(eyeMid.x, mouthY, true)
      if (skinDepth !== null && hairDepth !== null && hairDepth - skinDepth > radius * 0.12) mouthY -= radius * 0.25
    }
  }
  const colDepth = new Float32Array(13)
  for (let c = 0; c < 13; c += 1) {
    const x = eyeMid.x + (c / 12 * 2 - 1) * mouthHalfWidth
    let depth = surface.depthAt(x, mouthY) ?? surface.depthAt(eyeMid.x, mouthY) ?? eyeMid.dot(forward) - radius * 0.1
    if (hasFacialHair) {
      for (let k = -3; k <= 3; k += 1) {
        const hair = surface.depthAt(x, mouthY + k * radius * 0.22, true)
        if (hair !== null) depth = Math.max(depth, hair)
      }
    }
    colDepth[c] = depth + radius * (hasFacialHair ? 0.11 : 0.05)
  }
  // A rigid moustache reads as a grin: bend it with the mouth corners, and shade it when it is
  // light (see avatarFaceHair.ts).
  let hairShade: FacialHairShade | null = null
  if (hasFacialHair && hairMaterial && hairMaterial.color) {
    const hairLuma = hairMaterial.color.r * 0.299 + hairMaterial.color.g * 0.587 + hairMaterial.color.b * 0.114
    let hairMesh: THREE.SkinnedMesh | null = null
    model.traverse(object => {
      const mesh = object as THREE.SkinnedMesh
      if (!hairMesh && mesh.isSkinnedMesh && !Array.isArray(mesh.material) && mesh.material === hairMaterial) hairMesh = mesh
    })
    const hm = hairMesh as THREE.SkinnedMesh | null
    const hi = hm ? hm.skeleton.bones.indexOf(headBone) : -1
    if (hm && hi >= 0) {
      const toHead = new THREE.Matrix4().multiplyMatrices(hm.skeleton.boneInverses[hi]!, hm.bindMatrix)
      const edgeY = mouthY + radius * HAIR_EDGE_OFFSET
      let outline: THREE.SkinnedMesh | null = null
      model.traverse(object => {
        const mesh = object as THREE.SkinnedMesh
        if (!outline && mesh.isSkinnedMesh && mesh.name === `${hm.name}-outline`) outline = mesh
      })
      hairShade = installFacialHairShade(hairMaterial, hm, toHead, edgeY, radius, eyeMid.x, {
        light: hairLuma > 0.35,
        outline,
      })
    }
  }
  const mouthGeometry = createMouthGeometry()
  geometries.push(mouthGeometry.geometry)
  const mouthOrigin = new THREE.Vector3(eyeMid.x, mouthY, 0)
  // Remove the forward component from the origin: depth is added per column.
  mouthOrigin.addScaledVector(forward, -mouthOrigin.dot(forward))
  const mouth = createMouth({
    ...mouthGeometry,
    material: mouthMaterial,
    halfWidth: mouthHalfWidth,
    lip: radius * (hasFacialHair ? 0.11 : 0.15),
    origin: mouthOrigin,
    forward: basis.forward,
    right: basis.right,
    up: basis.up,
    colDepth,
    skinColor: skin,
    hairColor: null,
    toneAmount: personality.lipTone,
    facialHair: hasFacialHair,
  })
  const moustache = hairShade?.moustache ?? null
  if (moustache) {
    // The lips never draw over the moustache: the mouth is clipped to its (bent) lower edge.
    const edge = new Float32Array(moustache.lowerEdge.length)
    for (let b = 0; b < edge.length; b += 1) edge[b] = moustache.lowerEdge[b]! - mouthY
    mouth.hairClip = { edge, halfWidth: moustache.halfWidth * radius, liftL: 0, liftR: 0, centre: 0 }
  }
  headBone.add(mouth.mesh)

  // ---- brows + skin decals (one overlay mesh) ----
  const browSplit = browPoints.length > 6 ? splitBySide(browPoints) : null
  const browSpecs = eyes.map((eye, i) => {
    const painted = eye.side === 1 ? browSplit?.right : browSplit?.left
    const eyeCenter = eyeCenters[i]!
    const paintedCenter = painted?.getCenter(new THREE.Vector3())
    const restY = paintedCenter
      ? THREE.MathUtils.clamp(paintedCenter.y, eyeCenter.y + radius * 0.46, eyeCenter.y + radius * 0.95)
      : eyeCenter.y + radius * 0.66
    const paintedWidth = painted ? painted.max.x - painted.min.x : radius * 1.4
    return {
      side: eye.side,
      cx: eyeCenter.x + eye.side * radius * 0.1,
      // Behind opaque shades the brows sit above the frames, not through the lenses.
      // Behind glasses the brows sit a touch lower, so a hard hat's brim or a fringe never swallows them.
      cy: lenses ? restY - radius * 0.02 : restY + (eyewear === 'shades' ? radius * 0.34 : 0),
      length: THREE.MathUtils.clamp(paintedWidth * 1.1, radius * 1.15, radius * 1.65),
      thickness: radius * 0.22 * personality.browThickness,
    }
  })
  const mouthCorner = radius * 0.98 * 0.98
  const noseX = eyeMid.x
  const eyeY = eyeMid.y
  const r = radius
  const decal = (
    kind: DecalKind, x: number, y: number, hw: number, hh: number, rot: number, sprite: 'blob' | 'line', color: string
  ): DecalSpec => ({ kind, x, y, hw, hh, rot, sprite, color })
  const creaseAngle = (side: number) => {
    // From beside the nose down to the mouth corner.
    const from = { x: noseX + side * r * 0.62, y: eyeY - r * 1.5 }
    const to = { x: noseX + side * mouthCorner, y: mouthY + r * 0.18 }
    return {
      x: (from.x + to.x) / 2, y: (from.y + to.y) / 2,
      hw: Math.hypot(to.x - from.x, to.y - from.y) / 2,
      rot: Math.atan2(to.y - from.y, to.x - from.x),
    }
  }
  const creasePos = creaseAngle(1)
  const creaseNeg = creaseAngle(-1)
  const decalSpecs: DecalSpec[] = [
    decal('pallor', noseX, eyeY - r * 0.9, r * 1.9, r * 2.2, 0, 'blob', '#a9b7a4'),
    decal('blushA', noseX + r * 1.75, eyeY - r * 1.3, r * 1.15, r * 0.9, 0, 'blob', '#ff5a58'),
    decal('blushB', noseX - r * 1.75, eyeY - r * 1.3, r * 1.15, r * 0.9, 0, 'blob', '#ff5a58'),
    decal('bagA', eyeCenters[0]!.x, eyeCenters[0]!.y - r * 0.74, r * 0.66, r * 0.2, 0, 'blob', '#8a4f58'),
    decal('bagB', eyeCenters[1]!.x, eyeCenters[1]!.y - r * 0.74, r * 0.66, r * 0.2, 0, 'blob', '#8a4f58'),
    decal('nose', noseX, eyeY - r * 1.15, r * 0.24, r * 0.55, 0, 'blob', '#ffffff'),
    decal('forehead', noseX, eyeY + r * 1.95, r * 1.25, r * 0.55, 0, 'blob', '#ffffff'),
    decal('cheekA', noseX + r * 1.6, eyeY - r * 0.95, r * 0.5, r * 0.3, 0.35, 'blob', '#ffe2c8'),
    decal('cheekB', noseX - r * 1.6, eyeY - r * 0.95, r * 0.5, r * 0.3, -0.35, 'blob', '#ffe2c8'),
    decal('creaseA', creasePos.x, creasePos.y, creasePos.hw, r * 0.16, creasePos.rot, 'line', '#4a2418'),
    decal('creaseB', creaseNeg.x, creaseNeg.y, creaseNeg.hw, r * 0.16, creaseNeg.rot, 'line', '#4a2418'),
    decal('furrow', noseX, eyeY + r * 0.8, r * 0.36, r * 0.13, Math.PI / 2, 'line', '#4a2418'),
    decal('noseWrinkle', noseX, eyeY - r * 0.4, r * 0.5, r * 0.11, 0, 'line', '#4a2418'),
  ]
  const atlasTexture = acquireOverlayAtlas()
  const overlayMaterial = createOverlayMaterial(atlasTexture, gradientMap)
  created.push(overlayMaterial)
  const overlay = createOverlay({
    material: overlayMaterial,
    radius,
    basis,
    browSpecs,
    depthAt: (x, y) => surface.depthAt(x, y) ?? eyeMid.dot(forward) + r * 0.1,
    decalSpecs,
    browColor,
  })
  headBone.add(overlay.mesh)

  // Gentle skin grade: knock the saturation back a touch so warm skins stop reading as brick
  // red. Wrapped on the shared skin material (hands and body too) and undone on dispose.
  let restoreSkin: (() => void) | null = null
  if (skinSource) {
    const previous = skinSource.onBeforeCompile
    const previousKey = skinSource.customProgramCacheKey
    skinSource.onBeforeCompile = (shader, renderer) => {
      previous.call(skinSource, shader, renderer)
      shader.fragmentShader = shader.fragmentShader.replace(
        '#include <opaque_fragment>',
        `{ float skinLuma = dot(outgoingLight, vec3(0.299, 0.587, 0.114)); outgoingLight = mix(vec3(skinLuma), outgoingLight, ${SKIN_SATURATION.toFixed(2)}); }
#include <opaque_fragment>`
      )
    }
    skinSource.customProgramCacheKey = () => 'avatar-skin-grade-v1'
    skinSource.needsUpdate = true
    restoreSkin = () => {
      skinSource.onBeforeCompile = previous
      skinSource.customProgramCacheKey = previousKey
      skinSource.needsUpdate = true
    }
  }
  paintOver(materials, /^eye$/i, skinColor)
  paintOver(materials, /^eyebrows?$/i, skinColor)
  // The painted eye/brow patches are little raised slabs that catch the light as pale
  // rectangles once real brows sit on top: drop them (the skin underneath is intact).
  const hidden: THREE.Material[] = []
  for (const material of materials) {
    if (/^(eye|eyebrows?)$/i.test(material.name) && material.visible) {
      material.visible = false
      hidden.push(material)
    }
  }
  if (skinSource) {
    for (const material of materials) {
      if (/^(eye|eyebrows?)$/i.test(material.name) && (material as THREE.MeshToonMaterial).color) {
        skinFollowers.push(material as THREE.MeshToonMaterial)
      }
    }
  }

  // Opaque sunglasses hide the eyes (and brows sit above the frames).
  const shaded = eyewear === 'shades'
  for (const eye of eyes) eye.root.visible = !shaded

  // Forehead spot: above the brows, on the skin surface (measured, like the eyes).
  // Sized from the head's width at eye level, sitting just above the brows / glasses frames.
  let skinMinX = Infinity
  let skinMaxX = -Infinity
  let skinTop = -Infinity
  for (const point of skinPoints) {
    skinTop = Math.max(skinTop, point.y)
    if (Math.abs(point.y - center.y) < radius * 1.5) {
      skinMinX = Math.min(skinMinX, point.x)
      skinMaxX = Math.max(skinMaxX, point.x)
    }
  }
  const headWidth = Number.isFinite(skinMinX) && skinMaxX > skinMinX ? skinMaxX - skinMinX : radius * 7
  const foreheadSize = headWidth * 0.6
  const foreheadY = Math.min(
    center.y + radius * 2.4 + foreheadSize * 0.5,
    Number.isFinite(skinTop) ? skinTop - foreheadSize * 0.3 : Infinity
  )
  const foreheadProbe = new THREE.Vector3(center.x, Math.max(foreheadY, center.y + radius * 1.8), 0)
  let foreheadDepth = -Infinity
  for (const point of skinPoints) {
    if (Math.abs(point.x - foreheadProbe.x) < radius * 2 && Math.abs(point.y - foreheadProbe.y) < radius * 1.2) {
      foreheadDepth = Math.max(foreheadDepth, point.dot(forward))
    }
  }
  if (!Number.isFinite(foreheadDepth)) foreheadDepth = center.dot(forward) + radius * 0.2
  const foreheadPosition = foreheadProbe.clone().addScaledVector(forward, foreheadDepth + radius * 0.12 - foreheadProbe.dot(forward))
  // The forehead leans back: tip the sticker's normal up a little.
  const foreheadQuaternion = quaternion.clone().multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), -0.28))

  const input: FaceInput = { delta: 0, blink: 0, lookX: 0, lookY: 0, reducedMotion: false }
  const context = createFaceContext()
  const targets = createGazeTargets()
  return {
    headBone,
    forehead: { position: foreheadPosition, quaternion: foreheadQuaternion, unit: radius, size: foreheadSize },
    eyes,
    overlay,
    mouth,
    materials: created,
    geometries,
    skinFollowers,
    skinSource,
    personality,
    emotion: createEmotionState(seed),
    gazeState: createGazeState(seed),
    gazeTargets: targets,
    input,
    context,
    targets,
    gazeEyes: eyes.map(eye => ({ position: eye.root.position, quaternion: eye.root.quaternion, baseYaw: eye.side * 0.22 })),
    gazeOpts: { instant: false, heavy: 0, fallbackYaw: 0, fallbackPitch: 0, tripping: false, drunk: 0, closed: false, still: false },
    eyewear,
    hiddenMaterials: hidden,
    browContrast,
    restoreSkin,
    hairShade,
    skeletons: collectSkeletons(model),
    sceneHooked: false,
    scene: null,
    emote: null,
    state: {
      seed,
      time: 0,
      frame: 0,
      accumDelta: 0,
      strideFrame: 0,
      phase: Math.floor(seed * 1000) % 3,
      dim: 1,
      pupil: 0,
      debugWeights: new Float32Array(EMOTION_COUNT),
      lossStreak: 0,
      prevLoser: false,
      prevWinner: false,
      lastBrowAlpha: -1,
      mouthShape: { cornerL: 0, cornerR: 0, open: 0, width: 1, press: 0, purse: 0, teeth: 0, shift: 0 },
      browParams: { inner: [0, 0], outer: [0, 0], arch: 0, furrow: 0, dip: [0, 0], thick: 1 },
      alphas: {},
    },
  }
}

const LEGACY_MOOD_TO_EMOTION: Record<FaceMood, FaceEmotion | null> = {
  neutral: null,
  focused: 'focused',
  surprised: 'surprised',
  happy: 'happy',
  sad: 'sad',
  bored: 'bored',
}

interface FaceDebug {
  /** An emotion name, a legacy mood, or a weights map. */
  emotion?: string | Record<string, number>
  /** Force the gaze target: camera | board | pot | cards | acting | other | away. */
  gaze?: string
  /** Force eyelid closure 0..1. */
  blink?: number
  /** Skip smoothing (snap to the target). */
  instant?: boolean
  /** Extra channel overrides, e.g. { pupil: 1, red: 1, pallor: 1 }. */
  channels?: Record<string, number>
  /** Freeze natural blinking and micro-motion for stable stills. */
  still?: boolean
  /** Overrides applied to the emotion context after the director ran (e.g. { winner: true }). */
  context?: Partial<FaceContext>
  /** Lock the debug camera onto the face with this seed (dev screenshots). */
  cam?: { seed: number; dist: number; yaw?: number; fov?: number }
}

const GAZE_DEBUG: Record<string, number> = {
  camera: GAZE.viewer, viewer: GAZE.viewer, board: GAZE.board, pot: GAZE.pot, cards: GAZE.cards,
  acting: GAZE.acting, other: GAZE.other, away: GAZE.away,
}

function readDebug(): FaceDebug | null {
  if (process.env.NODE_ENV === 'production') return null
  return ((globalThis as { __faceDebug?: FaceDebug }).__faceDebug) ?? null
}

const scratchLight = new THREE.Vector3()
const scratchInv = new THREE.Matrix4()
const scratchSkin = new THREE.Color()
const LIGHT_WORLD = new THREE.Vector3(-0.22, 0.86, 0.46).normalize()

const clamp = THREE.MathUtils.clamp

/**
 * Moustache tip lift (eye radii) for a mouth corner, measured from that corner's RESTING height (so a
 * resting smirk or idle drift never turns into a sneer): a frown droops the tips, a smile lifts them,
 * both capped by the moustache's size; a gaping (not smiling) mouth pulls them down a little.
 * `rest` levels an upturned crescent at rest (from the moustache's measured shape).
 */
function moustacheLift(corner: number, restCorner: number, halfWidth: number, rest: number, smirk: number) {
  // A small dead zone: idle drift and faint in-hand asymmetry leave the moustache level.
  const raw = corner - restCorner
  const d = raw > 0 ? Math.max(0, raw - 0.1) : Math.min(0, raw + 0.1)
  // The lifted side of a smirk rises further and faster (the corner itself is hidden under the hair).
  // It also drops the rest levelling on that side, so the tip kinks up past the moustache's own crescent.
  const upCap = (0.28 + 0.2 * smirk) * halfWidth
  const bend = d < 0 ? Math.max(-Math.min(0.38 * halfWidth, 0.5), d * 0.9) : Math.min(upCap, d * (0.55 + 0.45 * smirk))
  return rest * (1 - smirk) + bend
}

/** Largest moustache tip motion per second (eye radii), so a frame hitch never snaps it. */
const MOUSTACHE_TIP_RATE = 3

/** Applies emotion, blink, gaze, lids, brows, mouth and skin decals for this frame. */
export function updateAvatarFace(face: AvatarFaceRig, input: FaceInput) {
  if (!face.sceneHooked) hookSkeletonSync(face)
  else if (face.scene) ensureSceneHook(face.scene)
  if (input.skip) return
  const costStart = process.env.NODE_ENV !== 'production' ? performance.now() : 0
  updateAvatarFaceInner(face, input)
  if (costStart) {
    const cost = ((globalThis as { __faceCost?: { ms: number; calls: number; cur: number } }).__faceCost ??= { ms: 0, calls: 0, cur: 0 })
    const spent = performance.now() - costStart
    cost.ms += spent
    cost.cur += spent
    cost.calls += 1
  }
}

function updateAvatarFaceInner(face: AvatarFaceRig, input: FaceInput) {
  const debug = readDebug()
  const state = face.state
  const delta = input.delta === input.delta ? Math.min(0.1, Math.max(0, input.delta)) : 0.016
  const instant = input.reducedMotion || Boolean(debug?.instant)
  state.frame += 1
  // Far faces update at a reduced rate already (director); beyond that skip decals every other update.
  const skipDetail = (input.distance ?? 0) > 9 && (state.frame & 1) === 1

  // ---- emotion ----
  const weights = state.debugWeights
  let debugWeights: Float32Array | null = null
  if (debug?.emotion !== undefined) {
    weights.fill(0)
    if (typeof debug.emotion === 'string') {
      const name = (LEGACY_MOOD_TO_EMOTION as Record<string, FaceEmotion | null>)[debug.emotion] ?? debug.emotion
      const index = name ? EMOTION_INDEX[name as FaceEmotion] : undefined
      if (index !== undefined) weights[index] = 1
    } else {
      for (const [key, value] of Object.entries(debug.emotion)) {
        const index = EMOTION_INDEX[key as FaceEmotion]
        if (index !== undefined) weights[index] = value
      }
    }
    debugWeights = weights
  } else if (!input.hasContext) {
    weights.fill(0)
    const legacy = input.mood ? LEGACY_MOOD_TO_EMOTION[input.mood] : null
    if (legacy) weights[EMOTION_INDEX[legacy]] = 1
    debugWeights = weights
  }
  if (debug?.context) Object.assign(face.context, debug.context)
  const distance = input.distance !== undefined && Number.isFinite(input.distance) ? input.distance : 0
  face.emotion.boost = clamp((distance - 4) / 6, 0, 1) * 0.5
  updateEmotion(face.emotion, face.context, face.personality, delta, instant, debugWeights)
  const p = face.emotion.params
  if (debug?.channels) {
    for (const [key, value] of Object.entries(debug.channels)) {
      const channel = (CH as Record<string, number>)[key]
      if (channel !== undefined) p[channel] = value
    }
  }
  state.time = face.emotion.time
  // How lopsided the smile is beyond the resting habit (+: the dominant "A" side is up), 0..1.
  let hairSmirk = 0
  if (face.mouth.facialHair) {
    // A smirk corner hides under the moustache: carry it with that side's cheek and lower lid.
    const asym = p[CH.smileA]! - p[CH.smileB]! - 0.4 * face.personality.baseSmile
    hairSmirk = clamp((Math.abs(asym) - 0.12) / 0.45, 0, 1) * Math.sign(asym)
    if (hairSmirk > 0) p[CH.lidLA] = Math.min(1, p[CH.lidLA]! + hairSmirk * 0.32)
    else if (hairSmirk < 0) p[CH.lidLB] = Math.min(1, p[CH.lidLB]! - hairSmirk * 0.32)
    // The moustache hides most of the mouth, so the smile also reads through cheeks and eyes.
    const smile = Math.max(0, (p[CH.smileA]! + p[CH.smileB]!) * 0.5 - 0.08)
    p[CH.lidLA] = Math.min(1, p[CH.lidLA]! + smile * 0.32)
    p[CH.lidLB] = Math.min(1, p[CH.lidLB]! + smile * 0.32)
    // ...and so does a frown: brows push further from rest, the furrow deepens, the upper lids
    // sag and the lower lids tighten, so a sad or angry face never leans on the mouth alone.
    const frown = clamp(-(p[CH.smileA]! + p[CH.smileB]!) * 0.5, 0, 1)
    if (frown > 0.01) {
      const gain = 1 + frown * 0.45
      p[CH.browIA] = p[CH.browIA]! * gain
      p[CH.browIB] = p[CH.browIB]! * gain
      p[CH.browOA] = p[CH.browOA]! * gain
      p[CH.browOB] = p[CH.browOB]! * gain
      p[CH.furrow] = Math.min(1, p[CH.furrow]! + frown * 0.3)
      p[CH.lidUA] = p[CH.lidUA]! - frown * 0.1
      p[CH.lidUB] = p[CH.lidUB]! - frown * 0.1
      p[CH.lidLA] = Math.min(1, p[CH.lidLA]! + frown * 0.15)
      p[CH.lidLB] = Math.min(1, p[CH.lidLB]! + frown * 0.15)
    }
    p[CH.smileA] += FACIAL_HAIR_SMILE_BIAS
    p[CH.smileB] += FACIAL_HAIR_SMILE_BIAS
  }

  // ---- blink ----
  const arousal = emotionArousal(face.emotion)
  const heavy = emotionHeaviness(face.emotion)
  const still = Boolean(debug?.still)
  const forced = debug?.emotion !== undefined ? (debug.blink ?? 0) : Math.max(input.blink, debug?.blink ?? 0)
  let blink = instant || still ? 0 : updateBlink(face.emotion, face.personality, face.gazeState.blinkKick)
  face.gazeState.blinkKick = false
  blink = Math.max(blink, forced)

  // ---- gaze ----
  const gazeState = face.gazeState
  const headWorld = face.headBone.matrixWorld
  scratchInv.copy(headWorld).invert()
  if (debug?.gaze && GAZE_DEBUG[debug.gaze] !== undefined) {
    gazeState.kind = GAZE_DEBUG[debug.gaze]!
    gazeState.fixUntil = face.emotion.time + 1e6
  } else if (gazeState.fixUntil > face.emotion.time + 1e5) {
    gazeState.fixUntil = face.emotion.time
  }
  const gazeOpts = face.gazeOpts
  gazeOpts.instant = instant
  gazeOpts.heavy = heavy
  gazeOpts.fallbackYaw = clamp(input.lookX, -1, 1) * 0.3
  gazeOpts.fallbackPitch = -clamp(input.lookY, -1, 1) * 0.2
  gazeOpts.tripping = face.context.tripping
  gazeOpts.drunk = face.context.drunk
  gazeOpts.closed = face.context.passedOut
  gazeOpts.still = still
  const kicked = updateGaze(
    gazeState,
    input.hasContext || debug?.gaze ? face.targets : null,
    scratchInv,
    face.gazeEyes,
    face.personality,
    face.emotion.time,
    delta,
    gazeOpts
  )
  // Big gaze shifts are usually accompanied by a blink.
  // A NaN in the gaze (bad target position) must never stick: recover to a neutral look.
  for (let e = 0; e < 2; e += 1) {
    if (!(gazeState.yaw[e]! === gazeState.yaw[e]!)) gazeState.yaw[e] = 0
    if (!(gazeState.pitch[e]! === gazeState.pitch[e]!)) gazeState.pitch[e] = 0
  }
  if (kicked && !instant && !still && face.emotion.time - gazeState.jumpedAt < 0.05) gazeState.blinkKick = faceRandomBlink(face)

  if (debug?.cam && Math.abs(debug.cam.seed - state.seed) < 1e-9) lockDebugCamera(face, debug.cam)
  // ---- dim (folded players sit in shade) ----
  const dimTarget = input.folded ? 0.62 : 1
  state.dim += (dimTarget - state.dim) * (instant ? 1 : 1 - Math.exp(-delta * 5))

  // Key light in Head space, for the catch-lights.
  scratchLight.copy(LIGHT_WORLD).transformDirection(scratchInv)

  // ---- eyes ----
  const time = face.emotion.time
  const smirkSide = face.personality.smirkSide
  const pupilNoise = still ? 0 : Math.sin(time * 1.9 + state.seed * 30) * 0.006 + Math.sin(time * 4.3 + state.seed * 11) * 0.003
  const pupilBase = 0.19 + p[CH.pupil]! * 0.085 + pupilNoise
  state.pupil = pupilBase
  const redness = clamp(p[CH.red]! + 0.14 * (1 - Math.min(1, blink)) * heavy, 0, 1)
  for (let i = 0; i < face.eyes.length; i += 1) {
    const eye = face.eyes[i]!
    const isA = eye.side === smirkSide
    const lidU = isA ? p[CH.lidUA]! : p[CH.lidUB]!
    const lidL = isA ? p[CH.lidLA]! : p[CH.lidLB]!
    const browI = isA ? p[CH.browIA]! : p[CH.browIB]!
    const browO = isA ? p[CH.browOA]! : p[CH.browOB]!
    const u = eye.uniforms
    // An eye roll takes over from wherever the eyes were looking: up and over, relative to straight ahead.
    const rollHand = 1 - face.emotion.rollEnv
    const eyePitch = Math.min(0.46, gazeState.pitch[i]! * rollHand + face.emotion.rollPitch)
    gazeVector(gazeState.yaw[i]! * rollHand + face.emotion.rollYaw, eyePitch, u.uGaze.value)
    // Lids follow the eyeball: looking down lowers the upper lid, up lifts it.
    const follow = eyePitch * 0.17
    const open = clamp((lidU + follow) * (1 - blink), 0, 1.32)
    const lower = clamp(lidL, -0.4, 1)
    const lowerAmp = 0.17 * (1 - 0.85 * lower) * (1 - 0.3 * blink)
    const tilt = 0.055 + 0.035 * (browO - browI) * 0.5
    u.uAper.value.set(0.3, Math.max(0.005, lowerAmp), EYE_APERTURE_HALF_WIDTH, tilt)
    u.uState.value.set(open, 0.85 + 0.2 * face.personality.expressiveness, 0.5 + 0.22 * (1 - Math.min(1, open)), state.dim)
    u.uIris.value.set(0.5, clamp(pupilBase * 1.12, 0.11, 0.34), 0.62, 1 + 0.5 * p[CH.sweat]! + 0.25 * heavy)
    // Catch-light offset from the key light, expressed in the eye's local axes.
    const lx = scratchLight.x * (eye.side === 1 ? 1 : 1) * 0.85
    const ly = scratchLight.y * 0.85
    const len = Math.hypot(lx, ly) || 1
    const scale = Math.min(1, 0.62 / len)
    u.uLight.value.set(lx * scale + (eye.side === 1 ? -0.05 : 0.05), ly * scale, redness, 1)
    u.uSclera.value.setRGB(0.95, 0.925 - 0.02 * p[CH.pallor]!, 0.885 - 0.03 * p[CH.pallor]!)
  }
  if (face.skinSource) {
    for (const follower of face.skinFollowers) follower.color.copy(face.skinSource.color)
  }
  // ---- brows ----
  if (!skipDetail) {
    const bp = state.browParams
    const eyeIsA0 = face.eyes[0]!.side === smirkSide
    const blinkDip = blink * 0.5
    bp.inner[0] = eyeIsA0 ? p[CH.browIA]! : p[CH.browIB]!
    bp.inner[1] = eyeIsA0 ? p[CH.browIB]! : p[CH.browIA]!
    bp.outer[0] = eyeIsA0 ? p[CH.browOA]! : p[CH.browOB]!
    bp.outer[1] = eyeIsA0 ? p[CH.browOB]! : p[CH.browOA]!
    bp.arch = p[CH.arch]!
    bp.furrow = p[CH.furrow]!
    const lowerA = clamp(eyeIsA0 ? p[CH.lidLA]! : p[CH.lidLB]!, 0, 1)
    const lowerB = clamp(eyeIsA0 ? p[CH.lidLB]! : p[CH.lidLA]!, 0, 1)
    bp.dip[0] = blinkDip + lowerA * 0.35
    bp.dip[1] = blinkDip + lowerB * 0.35
    // Thicker brows on far faces (and dark skin) so they still carry the expression.
    bp.thick = (1 + 0.5 * clamp((distance - 4) / 8, 0, 1)) * face.browContrast
    updateBrows(face.overlay, bp)

    // ---- mouth ----
    const shape = state.mouthShape
    const smileA = p[CH.smileA]!
    const smileB = p[CH.smileB]!
    // Eye index 0 is the +x side, so it owns the mouth's right corner.
    shape.cornerR = smirkSide === 1 ? smileA : smileB
    shape.cornerL = smirkSide === 1 ? smileB : smileA
    // A yawn stretches the jaw past the channel's range (a surprised "O" tops out at 0.9).
    shape.open = p[CH.open]! * (1 + 0.4 * face.context.yawn)
    if (face.hairShade) {
      // Neutral and frowning faces get the full lip shadow; a smile lets the moustache stay bright.
      const smileAvgHair = (smileA + smileB) * 0.5
      face.hairShade.uniforms.uHairShade.value.x = clamp(0.4 - smileAvgHair * 0.9 + p[CH.press]! * 0.3 + p[CH.furrow]! * 0.2, 0, 1)
    }
    // A wide-open mouth (surprise, laugh) is symmetric: pull the two corners together.
    const evenOut = Math.min(1, shape.open * 1.6)
    const cornerMean = (shape.cornerL + shape.cornerR) * 0.5
    shape.cornerL += (cornerMean - shape.cornerL) * evenOut
    shape.cornerR += (cornerMean - shape.cornerR) * evenOut
    if (face.hairShade) {
      // The moustache follows the mouth corners (without the facial-hair smile bias): tips droop on
      // a frown, one side lifts on a smirk, the upper lip rises when the mouth opens or snarls.
      const bend = face.hairShade.uniforms.uHairBend.value
      const person = face.personality
      const restA = 0.05 + person.baseSmile + FACIAL_HAIR_SMILE_BIAS
      const restB = 0.05 + person.baseSmile * 0.6 + FACIAL_HAIR_SMILE_BIAS
      const width = bend.z
      const level = -clamp((face.hairShade.moustache?.tipRise ?? 0) * 0.85, 0, 0.4 * width)
      const smirkR = Math.max(0, smirkSide === 1 ? hairSmirk : -hairSmirk)
      const smirkL = Math.max(0, smirkSide === 1 ? -hairSmirk : hairSmirk)
      const wantL = moustacheLift(shape.cornerL, smirkSide === 1 ? restB : restA, width, level, smirkL)
      const wantR = moustacheLift(shape.cornerR, smirkSide === 1 ? restA : restB, width, level, smirkR)
      // An open, unsmiling mouth (surprise, shock) lifts the moustache's middle so an "O" shows under it.
      const unsmiling = clamp(1 - 2 * Math.max(0, (shape.cornerL + shape.cornerR) * 0.5 - FACIAL_HAIR_SMILE_BIAS), 0, 1)
      const wantC = shape.open * (0.12 + 0.1 * unsmiling) + p[CH.teeth]! * 0.04 - p[CH.press]! * 0.04
      if (instant) {
        bend.x = wantL
        bend.y = wantR
        bend.w = wantC
      } else {
        const step = MOUSTACHE_TIP_RATE * Math.min(delta, 0.05)
        bend.x += clamp(wantL - bend.x, -step, step)
        bend.y += clamp(wantR - bend.y, -step, step)
        bend.w += clamp(wantC - bend.w, -step, step)
      }
      const clip = face.mouth.hairClip
      if (clip) {
        clip.liftL = bend.x * face.eyes[0]!.radius
        clip.liftR = bend.y * face.eyes[0]!.radius
        clip.centre = bend.w * face.eyes[0]!.radius
      }
    }
    shape.width = p[CH.width]!
    shape.press = p[CH.press]!
    shape.purse = p[CH.purse]!
    shape.teeth = p[CH.teeth]!
    if (face.mouth.facialHair) {
      // Under a moustache a gasp should read as a round "O", not a wide toothy "ah": narrower,
      // a touch rounder, fewer teeth.
      const unsmilingO = clamp(1 - 2 * Math.max(0, (smileA + smileB) * 0.5 - FACIAL_HAIR_SMILE_BIAS), 0, 1)
      const gasp = clamp(shape.open * 1.4, 0, 1) * unsmilingO
      shape.width -= 0.3 * gasp
      shape.purse = Math.min(1, shape.purse + 0.25 * gasp)
      shape.teeth *= 1 - 0.6 * gasp
    }
    shape.shift = p[CH.jaw]! * smirkSide * (1 - evenOut)
    ;(face.mouth.mesh.material as THREE.MeshToonMaterial).color.setScalar(state.dim)
    const skinForMouth = face.skinSource ? face.skinSource.color : scratchSkin
    updateMouth(face.mouth, shape, skinForMouth)
  }

  // ---- skin decals ----
  if (!skipDetail) {
    const a = state.alphas
    const smileAvg = (p[CH.smileA]! + p[CH.smileB]!) * 0.5
    const warmth = face.personality.warmth
    const sweat = p[CH.sweat]!
    // Drink shows as rosy cheeks here (the skin itself only warms a little, see flushCheeks).
    const flush = clamp(face.context.drunk / 10, 0, 1)
    const blush = Math.min(0.2 + 0.22 * flush, 0.04 + 0.02 * warmth + p[CH.blush]! * 0.3 + Math.max(0, smileAvg) * 0.04 + flush * 0.3)
    a.blushA = blush
    a.blushB = blush
    const tired = clamp(p[CH.pallor]! * 0.7 + p[CH.red]! * 0.35 + (1 - p[CH.lidUA]!) * 0.14 + heavy * 0.2 + arousal * 0.08, 0, 1)
    a.bagA = 0.015 + tired * 0.2
    a.bagB = 0.015 + tired * 0.2
    a.nose = 0.03 + 0.02 * Math.max(0, warmth) + sweat * 0.34
    a.forehead = 0.035 + sweat * 0.32
    const cheekLift = 0.012 + sweat * 0.22 + Math.max(0, smileAvg) * (face.mouth.facialHair ? 0.12 : 0.05)
    a.cheekA = cheekLift
    a.cheekB = cheekLift
    a.pallor = Math.min(0.25, p[CH.pallor]! * 0.3)
    const wrinkle = p[CH.wrinkle]!
    // creaseA sits on the +x side, which belongs to whichever of A/B that side is.
    const smilePlus = smirkSide === 1 ? p[CH.smileA]! : p[CH.smileB]!
    const smileMinus = smirkSide === 1 ? p[CH.smileB]! : p[CH.smileA]!
    const creaseGain = face.mouth.facialHair ? 1.7 : 1
    // Under a moustache the smirk side's cheek crease carries the lopsided smile.
    const smirkPlus = (smirkSide === 1 ? hairSmirk : -hairSmirk)
    a.creaseA = Math.max(0, smilePlus - 0.15) * 0.34 * creaseGain + wrinkle * 0.2 + Math.max(0, smirkPlus) * 0.22
    a.creaseB = Math.max(0, smileMinus - 0.15) * 0.34 * creaseGain + wrinkle * 0.2 + Math.max(0, -smirkPlus) * 0.22
    a.furrow = p[CH.furrow]! * 0.26
    a.noseWrinkle = Math.max(0, wrinkle - 0.1) * 0.5
    updateOverlayColors(face.overlay, a, 0.94, state.dim)
  }
}

const camMid = new THREE.Vector3()
const camFwd = new THREE.Vector3()
const camMat = new THREE.Matrix4()

/** Dev only: keeps the debug camera looking straight into this face, every frame. */
function lockDebugCamera(face: AvatarFaceRig, cam: NonNullable<FaceDebug['cam']>) {
  const stage = document.querySelector('.desktop-3d-stage') as (Element & { __pokerRuntime?: { debugCamera: unknown } }) | null
  const runtime = stage?.__pokerRuntime
  if (!runtime) return
  camMat.copy(face.headBone.matrixWorld)
  camMid.copy(face.eyes[0]!.root.position).add(face.eyes[1]!.root.position).multiplyScalar(0.5).applyMatrix4(camMat)
  camFwd.copy(face.overlay.basis.forward).transformDirection(camMat)
  const yaw = cam.yaw ?? 0
  const c = Math.cos(yaw)
  const s = Math.sin(yaw)
  const fx = camFwd.x * c + camFwd.z * s
  const fz = -camFwd.x * s + camFwd.z * c
  runtime.debugCamera = {
    position: [camMid.x + fx * cam.dist, camMid.y + camFwd.y * cam.dist, camMid.z + fz * cam.dist],
    lookAt: [camMid.x, camMid.y - 0.06, camMid.z],
    fov: cam.fov ?? 30,
  }
}

function faceRandomBlink(face: AvatarFaceRig) {
  // Roughly 60% of big gaze jumps come with a blink (deterministic per face and moment).
  return faceHash01(face.emotion.time * 3.1 + face.state.seed * 7) < 0.6
}

export function disposeAvatarFace(face: AvatarFaceRig | null) {
  if (!face) return
  face.hiddenMaterials.forEach(material => { material.visible = true })
  face.restoreSkin?.()
  face.hairShade?.restore()
  for (const skeleton of face.skeletons) unregisterSkeleton(skeleton)
  face.eyes.forEach(eye => eye.root.removeFromParent())
  face.overlay.mesh.removeFromParent()
  face.mouth.mesh.removeFromParent()
  face.materials.forEach(material => material.dispose())
  face.geometries.forEach(geometry => geometry.dispose())
  face.overlay.mesh.geometry.dispose()
  releaseOverlayAtlas()
}

/** Exposed for the debug snapshot tool (dev only). */
export function describeFace(face: AvatarFaceRig) {
  return {
    eyewear: face.eyewear,
    eyeRadius: face.eyes[0]?.radius,
    moustache: face.hairShade?.moustache
      ? { halfWidth: face.hairShade.moustache.halfWidth, tipRise: face.hairShade.moustache.tipRise, bend: face.hairShade.uniforms.uHairBend.value.toArray() }
      : null,
    personality: face.personality,
    channels: Array.from(face.emotion.params),
    gaze: { kind: face.gazeState.kind, yaw: [...face.gazeState.yaw], pitch: [...face.gazeState.pitch] },
  }
}
